export const MESSAGE = {
    GET_ADDRESS_SUCCESSFULLY: "Lấy địa chỉ thành công.",
    GET_ADDRESS_FAILED: "Lấy địa chỉ thất bại.",
    GET_PROFILE_FAILED: "Lấy thông tin người dùng thất bại.",
    CREATE_ADDRESS_SUCCESSFULLY: "Đã tạo địa chỉ thành công.",
    UPDATE_ADDRESS_SUCCESSFULLY: "Đã cập nhật địa chỉ thành công.",
    DELETE_ADDRESS_SUCCESSFULLY: "Đã xóa địa chỉ thành công.",
    LOGIN_SUCCESSFULLY: "Đăng nhập thành công.",
    LOGOUT_SUCCESSFULLY: "Đăng xuất thành công.",
    REGISTER_SUCCESSFULLY: "Đăng kí thành công. Vui lòng kiểm tra email!",
    CHANGE_PASSWORD_SUCCESSFULLY: "Đổi mật khẩu thành công.",
    CREATE_ADDRESS_FAILED: "Tạo địa chỉ thất bại.",
    UPDATE_ADDRESS_FAILED: "Cập nhật địa chỉ thất bại.",
    DELETE_ADDRESS_FAILED: "Xóa địa chỉ thất bại.",
    LOGIN_FAILED: "Đăng nhập thất bại.",
    LOGOUT_FAILED: "Đăng xuất thất bại.",
    REGISTER_FAILED: "Đăng ký thất bại.",
    CHANGE_PASSWORD_FAILED: "Đổi mật khẩu thất bại.",
    VERIFY_ACCOUNT_SUCCESSFULLY: "Xác minh tài khoản thành công. Vui lòng đăng nhập lại!",
    VERIFY_ACCOUNT_FAILED: "Xác minh tài khoản thất bại.",
    RESEND_OTP_SUCCESSFULLY: "Gửi OTP thành công.",
    RESEND_OTP_FAILED: "Gửi OTP thất bại.",
    FORGOT_PASSWORD_SUCCESSFULLY: "Xác minh tài khoản thành công.",
    FORGOT_PASSWORD_FAILED: "Xác minh tài khoản thất bại.",
    RESET_PASSWORD_SUCCESSFULLY: "Đặt lại mật khẩu thành công. Vui lòng đăng nhập với mật khẩu mới!",
    RESET_PASSWORD_FAILED: "Đặt lại mật khẩu thất bại. Vui lòng thử lại!",


}