import { Product } from ".";
const labubuImageTemp = 'https://product.hstatic.net/200000863773/product/remove-bg.ai_1724309504528_e64e21fdaf6f47339b2c211e441a66a2_grande.png'
// Sample product data
export const productData: Product[] = [
  {
    id: 1,
    title: "Baby Three - Pink Edition",
    category: "Baby Three",
    price: 29.99,
    image: labubuImageTemp,
    description: "Adorable Baby Three doll in pink outfit, perfect for collectors.",
  },
  {
    id: 2,
    title: "Baby Three - Blue Edition",
    category: "Baby Three",
    price: 29.99,
    image: labubuImageTemp,
    description: "Cute Baby Three doll in blue outfit, limited edition.",
  },
  {
    id: 3,
    title: "Labubu Classic",
    category: "Labubu",
    price: 39.99,
    image: labubuImageTemp,
    description: "Original Labubu doll with signature design.",
  },
  {
    id: 4,
    title: "Labubu Winter Edition",
    category: "Labubu",
    price: 44.99,
    image: labubuImageTemp,
    description: "Special winter themed Labubu with scarf and hat.",
  },
  {
    id: 5,
    title: "Dimoo Space Series",
    category: "Dimoo",
    price: 34.99,
    image: labubuImageTemp,
    description: "Dimoo doll in astronaut outfit, part of the space collection.",
  },
  {
    id: 6,
    title: "Baby Three - Special Edition",
    category: "Baby Three",
    price: 49.99,
    image: labubuImageTemp,
    description: "Limited special edition Baby Three with unique accessories.",
  },
  {
    id: 7,
    title: "Labubu Dragon Edition",
    category: "Labubu",
    price: 54.99,
    image: labubuImageTemp,
    description: "Mythical dragon-themed Labubu, collector's item.",
  },
  {
    id: 8,
    title: "Dimoo Rainbow Series",
    category: "Dimoo",
    price: 32.99,
    image: labubuImageTemp,
    description: "Colorful rainbow-themed Dimoo doll.",
  },
  {
    id: 9,
    title: "Baby Three - Holiday Edition",
    category: "Baby Three",
    price: 39.99,
    image: labubuImageTemp,
    description: "Festive holiday-themed Baby Three doll.",
  },
  {
    id: 10,
    title: "Labubu Glow Edition",
    category: "Labubu",
    price: 49.99,
    image: labubuImageTemp,
    description: "Special glow-in-the-dark Labubu doll.",
  },
  {
    id: 11,
    title: "Dimoo Flower Series",
    category: "Dimoo",
    price: 36.99,
    image: labubuImageTemp,
    description: "Dimoo doll with beautiful flower theme.",
  },
  {
    id: 12,
    title: "Baby Three - Pastel Collection",
    category: "Baby Three",
    price: 34.99,
    image: labubuImageTemp,
    description: "Baby Three doll in soft pastel colors.",
  },
  {
    id: 13,
    title: "Labubu Ocean Edition",
    category: "Labubu",
    price: 42.99,
    image: labubuImageTemp,
    description: "Ocean-themed Labubu with underwater accessories.",
  },
  {
    id: 14,
    title: "Dimoo Night Series",
    category: "Dimoo",
    price: 38.99,
    image: labubuImageTemp,
    description: "Dimoo doll with night sky theme and stars.",
  },
  {
    id: 15,
    title: "Baby Three - Collector's Edition",
    category: "Baby Three",
    price: 59.99,
    image: labubuImageTemp,
    description: "Rare collector's edition Baby Three with certificate.",
  },
]
