import type { Product } from "@/components/molecules/home/ProductCard"
const labubuImg = 'https://i.ebayimg.com/images/g/6oEAAeSwqHdn2D6v/s-l400.jpg'
export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Búp bê tùy chỉnh - Quần áo búp bê tùy chỉnh - Giá khác nhau",
    image: labubuImg,
    rating: 4.8,
    reviewCount: 9,
    currentPrice: 265252,
    originalPrice: 663130,
    discount: 60,
    freeShipping: true,
    seller: "Etsy seller",
  },
  {
    id: "2",
    title: "Búp bê chân dung cặp đôi, Búp bê cặp đôi tùy chỉnh, Giống như bạn",
    image: labubuImg,
    rating: 5.0,
    reviewCount: 476,
    currentPrice: 145889,
    originalPrice: 583556,
    discount: 75,
    location: "VN",
  },
  {
    id: "3",
    title: "Búp bê cặp đôi tùy chỉnh, Búp bê móc tùy chỉnh, Giống như bạn",
    image: labubuImg,
    rating: 4.5,
    reviewCount: 582,
    currentPrice: 362599,
    originalPrice: 1450396,
    discount: 75,
    location: "VN",
  },
  {
    id: "4",
    title: "Búp bê ảnh khuôn mặt tùy chỉnh, Quà tặng được cá nhân hóa",
    image: labubuImg,
    rating: 5.0,
    reviewCount: 936,
    currentPrice: 262599,
    originalPrice: 875330,
    discount: 70,
    freeShipping: true,
  },
  {
    id: "5",
    title: "Búp bê tùy chỉnh - Quần áo búp bê tùy chỉnh - Giá khác nhau",
    image: labubuImg,
    rating: 4.8,
    reviewCount: 9,
    currentPrice: 265252,
    originalPrice: 663130,
    discount: 60,
    freeShipping: true,
    seller: "Etsy seller",
  },
  {
    id: "6",
    title: "Búp bê Monster High Lot gồm 34 búp bê kèm quần áo, giày dép",
    image: labubuImg,
    rating: 4.7,
    reviewCount: 125,
    currentPrice: 7692308,
    seller: "Etsy seller",
  },
  {
    id: "7",
    title: "Quà tặng Ngày của Mẹ / Búp bê thú cưng tùy chỉnh cho gia đình lớn",
    image: labubuImg,
    rating: 5.0,
    reviewCount: 91,
    currentPrice: 5941645,
    freeShipping: true,
    location: "VN",
    seller: "Etsy seller",
  },
  {
    id: "8",
    title: "Rối tùy chỉnh, đồ trang trí Giáng sinh được cá nhân hóa",
    image: labubuImg,
    rating: 4.9,
    reviewCount: 715,
    currentPrice: 1445623,
    seller: "Etsy seller",
  },
  {
    id: "9",
    title: "Búp bê gia đình tùy chỉnh, Quà tặng gia đình, Quà tặng kỷ niệm",
    image: labubuImg,
    rating: 4.9,
    reviewCount: 328,
    currentPrice: 1852000,
    originalPrice: 3704000,
    discount: 50,
    location: "VN",
  },
  {
    id: "10",
    title: "Búp bê chân dung tùy chỉnh, Quà tặng sinh nhật, Quà tặng kỷ niệm",
    image: labubuImg,
    rating: 4.8,
    reviewCount: 215,
    currentPrice: 1250000,
    originalPrice: 2500000,
    discount: 50,
    freeShipping: true,
  },
  {
    id: "11",
    title: "Búp bê vải tùy chỉnh, Quà tặng cho bé, Búp bê handmade",
    image: labubuImg,
    rating: 4.7,
    reviewCount: 183,
    currentPrice: 850000,
    originalPrice: 1200000,
    discount: 30,
    location: "VN",
  },
  {
    id: "12",
    title: "Búp bê gỗ tùy chỉnh, Trang trí nhà cửa, Quà tặng độc đáo",
    image: labubuImg,
    rating: 4.6,
    reviewCount: 97,
    currentPrice: 1750000,
    freeShipping: true,
  },
  {
    id: "13",
    title: "Búp bê cưới tùy chỉnh, Quà tặng đám cưới, Trang trí bánh cưới",
    image: labubuImg,
    rating: 5.0,
    reviewCount: 156,
    currentPrice: 2350000,
    originalPrice: 3500000,
    discount: 33,
    location: "VN",
  },
  {
    id: "14",
    title: "Búp bê thú cưng tùy chỉnh, Quà tặng cho người yêu thú cưng",
    image: labubuImg,
    rating: 4.9,
    reviewCount: 112,
    currentPrice: 950000,
    originalPrice: 1500000,
    discount: 37,
    freeShipping: true,
  },
  {
    id: "15",
    title: "Búp bê siêu anh hùng tùy chỉnh, Quà tặng cho trẻ em",
    image: labubuImg,
    rating: 4.8,
    reviewCount: 78,
    currentPrice: 1150000,
    location: "VN",
  },
  {
    id: "16",
    title: "Búp bê nghề nghiệp tùy chỉnh, Quà tặng tốt nghiệp, Quà tặng công việc mới",
    image: labubuImg,
    rating: 4.7,
    reviewCount: 65,
    currentPrice: 1650000,
    originalPrice: 2200000,
    discount: 25,
    freeShipping: true,
  },
  {
    id: "17",
    title: "Búp bê anime tùy chỉnh, Quà tặng cho người hâm mộ anime",
    image: labubuImg,
    rating: 4.9,
    reviewCount: 203,
    currentPrice: 1850000,
    location: "VN",
  },
  {
    id: "18",
    title: "Búp bê sao thể thao tùy chỉnh, Quà tặng cho người hâm mộ thể thao",
    image: labubuImg,
    rating: 4.6,
    reviewCount: 87,
    currentPrice: 1950000,
    originalPrice: 2800000,
    discount: 30,
    freeShipping: true,
  },
  {
    id: "19",
    title: "Búp bê nhân vật lịch sử tùy chỉnh, Quà tặng giáo dục",
    image: labubuImg,
    rating: 4.8,
    reviewCount: 45,
    currentPrice: 2150000,
    location: "VN",
  },
  {
    id: "20",
    title: "Búp bê kỷ niệm tùy chỉnh, Quà tặng kỷ niệm ngày cưới",
    image: labubuImg,
    rating: 5.0,
    reviewCount: 132,
    currentPrice: 2650000,
    originalPrice: 3800000,
    discount: 30,
    freeShipping: true,
  },
]
