export { default as HomePage } from './home'
export { default as AdminDashboard } from './admin/dashboard'
export { default as LoginPage } from './auth/login'
export { default as RegisterPage } from './auth/register'
export { default as ForgotPasswordPage } from './auth/forgot-password'
export { default as ChangePasswordPage } from './auth/change-password'